### ISSUE TITLE
Error loading PDF

### ISSUE THREAD

**Issue by geobir** [francisgreenleaf/Reader#9]
When I to load this link:
```
https://personal.utdallas.edu/~otoole/CGS2301_S09/15_expert.pdf
```

**console**
`Error fetching article: Failed to extract meaningful content from the URL`

**server side**
`Reader/app.py", line 106, in fetch_article
    raise ValueError("Failed to extract meaningful content from the URL")
ValueError: Failed to extract meaningful content from the URL
ERROR:__main__:Error fetching article: Failed to extract meaningful content from the URL`

```python
@app.route("/fetch", methods=["POST"])
def fetch_article():
    url = request.json["url"]
    try:
        content = fetch_and_format_content(url)
        if not content.title or not content.content:
            raise ValueError("Failed to extract meaningful content from the URL")
        return jsonify({"content": content})
    except Exception as e:
        error_message = f"Error fetching article: {str(e)}"
        logger.error(error_message, exc_info=True)
        return jsonify({"error": error_message}), 400
```

-----

Other PDF like this one also produce the same error:
```
https://arxiv.org/pdf/2408.08339
```

**Comment by WilliamAGH** [comment]
@geobir here are some methods I used that might help:

1. Jina.ai PDF/URL parser: https://r.jina.ai/https://personal.utdallas.edu/~otoole/CGS2301_S09/15_expert.pdf
2. Here is another method that was successful also:
<img width="1285" alt="PDF screenshot" src="https://github.com/user-attachments/assets/d717202c-2709-49d2-9be6-fefed2cada99">

The second method loading the PDF relied upon:
    - langchain.chains.summarize: For loading the summarize chain
    - langchain.text_splitter: For splitting text into chunks
    - langchain.schema: For Document objects
    - PyPDF2: For reading PDF content
    - aiohttp: For asynchronously fetching PDF content from URLs
    - langchain_openai: For the ChatOpenAI model

You can checkout my [experimental repo](https://github.com/Experimental-Work/Stanford) for it if it helps!
